language: node_js
sudo: required
node_js:
  - 'node'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 10 # give xvfb some time to start
script:
  - travis_wait 30 yarn test
addons:
  chrome: stable
