export const GAME_SCORE_FACTOR = 42;

export const GAME_CARDS_FLIP_ANIMATION_DURATION = 600;
export const GAME_DELAY_BETWEEN_GAME_START_AND_FLIP_ALL_CARDS = 5000;
// export const GAME_DELAY_BETWEEN_GAME_START_AND_FLIP_ALL_CARDS = 600;
export const GAME_DELAY_BEFORE_FLIP_TO_BACKSIDE = 500;
export const GAME_DELAY_BEFORE_DISAPPEAR_ANIMATION = 100;
