export const GAME_SCORE_FACTOR = 42;

export const GAME_CARDS_FLIP_ANIMATION_DURATION = 600;
export const GAME_DELAY_BETWEEN_GAME_START_AND_FLIP_ALL_CARDS = 5000;
// export const GAME_DELAY_BETWEEN_GAME_START_AND_FLIP_ALL_CARDS = 600;
export const GAME_DELAY_BETWEEN_CARD_OPEN_AND_FLIP_START = 500;
export const GAME_DELAY_BETWEEN_CARD_OPEN_AND_DISAPPEAR_START = 100;
